### ISSUE TITLE
How to download and handle pretraining weights?

### ISSUE THREAD

**Issue by Huang-th** [UkcheolShin/CRM_RGBTSeg#1]
During the installation process, we did not find download_backbone_pt_weight.sh and convert_pth_to_pkl.sh file. Sincerely hope you provide them.

**Comment by UkcheolShin** [comment]
The scripts download backbone weights pre-trained in ImageNet 1K and 22K.
The pre-trained backbone weights are needed for the network training. 
And we don't open the training code at this stage. 
If you'd like to test our pre-trained model, you can download the model weights in the results section of README.md and follow the evaluation process.
E.g.,
CUDA_VISIBLE_DEVICES=0 python test.py --config-file ./configs/MFdataset/swin/CRM_swin_small_224.yaml --num-gpus 1 --name Eval_MF_CRM_swin_S --checkpoint "PATH for WEIGHT"

**Comment by UkcheolShin** [comment]
I released the entire training and evaluation source code. Thank you for waiting!
