### ISSUE TITLE
when can we use train.py and download the download_backbone_pt_weight

### ISSUE THREAD

**Issue by HarisIqbal89** [UkcheolShin/CRM_RGBTSeg#2]
First,please let me show my respect to your.CRM is a great work for RGB-T segmentation. Then,could you tell us when we can use train.py and download the download_backbone_pt_weight。
I am looking for your reply.

**Comment by HarisIqbal89** [comment]
please i am still waiting for the train.py!

**Comment by Markson-Young** [comment]
> please i am still waiting for the train.py!

me too!

**Comment by HarisIqbal89** [comment]
> > please i am still waiting for the train.py!
> 
> me too!

are you Chinese   :)

**Comment by Stark320** [comment]
same

**Comment by UkcheolShin** [comment]
I released the entire training and evaluation source code. Thank you for waiting!
