### ISSUE TITLE
download_backbone_pt_weight.sh and convert_pth_to_pkl.sh

### ISSUE THREAD

**Issue by sbjshxbxijs** [UkcheolShin/CRM_RGBTSeg#3]
when I run 
cd pretrained
sh download_backbone_pt_weight.sh
sh convert_pth_to_pkl.sh

In your repo, I don't find the file:download_backbone_pt_weight.sh and convert_pth_to_pkl.sh. Could you provide it ?

**Comment by UkcheolShin** [comment]
I released the entire training and evaluation source code. Thank you for waiting!
